# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7876c1e5c1a5b9ef31a0a8d9875c3665785b12600edc35954bb1dd0a28ded9dc58814ccabcdb3722cbbfd38b62022d4abc8059b859f1df850de9c1304cfb26ce

test:
  secret_key_base: ef2a8244dd8681851ee10cd936d8d575ef1337577c73c72b6a32f4675aff366302d490bb542bbd18786fcf2532dddfc026cfd450f820a844b9583b484f380d03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
